#!/bin/bash
# Step 2: the 30 evaluate jobs, run AFTER all 30 fit jobs from rerun_stage4_fix.sh have finished.
# Run once: bash evaluate_stage4_fix.sh
set -e

sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 0
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 0
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 0
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 1
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 1
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 1
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 2
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 2
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 2
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 3
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 3
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 3
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 4
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 4
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 4survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 4
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 0
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 0
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 0
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 1
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 1
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 1
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 2
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 2
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 2
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 3
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 3
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 3
sbatch jobs/dnn_env_terrain/evaluate_dnn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_dnn_env_terrain 42 5 4
sbatch jobs/pinn_env_terrain/evaluate_pinn_env_terrain.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain 42 5 4
sbatch jobs/pinn_env_terrain_k/evaluate_pinn_env_terrain_k.sh 6survey spatial_block_kfold stage4_all_environmental_pinn_env_terrain_k 42 5 4
