#!/bin/bash
# RUN THIS ON: your Mac, after squeue on the cluster shows tier 4_fit.sh's jobs COMPLETED.
# Tier 4 sync -- 150 fit jobs -> 75 run folders.
# This is the FULLY EXPLICIT version: the filter rules below are written out literally (not
# computed at runtime), so you can read exactly what will and won't be copied before running it.
# Safe to copy-paste this whole block directly into your own terminal instead of running this
# file, if you'd rather not run any script of mine against your cluster account.

FILTER_FILE=$(mktemp)
cat > "$FILTER_FILE" <<'FILTEREOF'
+ /spatial_block_kfold/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed42/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed42/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed43/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed43/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed44/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed44/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed45/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed45/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed46/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold0_seed46/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed42/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed42/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed43/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed43/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed44/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed44/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed45/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed45/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed46/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold1_seed46/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed42/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed42/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed43/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed43/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed44/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed44/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed45/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed45/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed46/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold2_seed46/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed42/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed42/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed43/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed43/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed44/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed44/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed45/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed45/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed46/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold3_seed46/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed42/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed42/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed43/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed43/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed44/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed44/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed45/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed45/***
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed46/
+ /spatial_block_kfold/clean_dnn_env_terrain_set2_spatial_block_kfold_fold4_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold0_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold1_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold2_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold3_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_k_set2_spatial_block_kfold_fold4_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold0_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold1_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold2_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold3_seed46/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed42/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed42/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed43/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed43/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed44/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed44/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed45/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed45/***
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed46/
+ /spatial_block_kfold/clean_pinn_env_terrain_set2_spatial_block_kfold_fold4_seed46/***
- /growth_curve_attribution/gnnwr/models/
- *
FILTEREOF

rsync -avz -e "ssh -J s2887183@student.ssh.inf.ed.ac.uk" \
  --filter="merge $FILTER_FILE" \
  s2887183@hastings.inf.ed.ac.uk:~/forest_diss/outputs/ \
  /Users/shreeyagorasia/UoE_Docs/Dissertation/forest_diss/outputs/

rm -f "$FILTER_FILE"
